- .github/workflows/ci:main.yml
- test/__snapshots__/button.test.tsx.snap
Will ensure `npm test`  runs and displays status for every PR. The goal is we catch PRs that break tests and thus that will ultimately prevent a successful publish.
> Add: CI testing flow for PR's and Pushes to main

- package-lock.json
- package.json
CI is failing because `@nrwl/cypress/package.json` is not found. This PR adds that package as a dev dependency.
> fix: install missing package for cypress CI

- libs/spark/CHANGELOG.md
- libs/spark/package.json
I forgot to run `npx nx version spark` after adding the icon library
> Bump version

- .github/workflows/npm-publish.yml
Also changes the slack notif to be minimal and spark-themed
> chore(cd): only publish on release

- libs/spark/src/theme/theme.ts
> fix: default MUI override of body font-size

- libs/spark/src/theme/colors.ts
- libs/spark/src/theme/theme.ts
- libs/spark/stories/colors.stories.tsx
> feat(palette): add new lighterGrey color

- libs/spark/src/Checkbox.tsx
- libs/spark/src/FormControlLabel.ts
- libs/spark/src/Radio.tsx
- libs/spark/src/theme/theme.ts
part of #75 
Shouldn't cause any visible changes
> feat(FormControlLabel): add global style

- libs/spark/src/Checkbox.tsx
- libs/spark/src/Radio.tsx
- libs/spark/src/theme/theme.ts
includes #80 (only first commit)
part of #75 
Also closes #84 -- needs a chromatic ui review / approve, see checks
> feat(Checkbox): add global styles and props

- libs/spark/src/Input.tsx
Includes #87 (only first commit)
Closes #55
> feat(Input): update default styles

- libs/spark/src/Input.tsx
- libs/spark/src/theme/theme.ts
> feat(Input): add global styles and props

- libs/spark/src/FormHelperText.ts
- libs/spark/src/Input.tsx
- libs/spark/src/theme/theme.ts
> feat(FormHelperText): add global styles

- libs/spark/src/Input.tsx
- libs/spark/src/InputLabel.ts
- libs/spark/src/theme/theme.ts
> feat(InputLabel): add global styles

- libs/spark/src/Dropdown.tsx
- libs/spark/src/MenuItem.tsx
- libs/spark/src/index.ts
- libs/spark/src/theme/theme.ts
- libs/spark/test/MenuItem.spec.tsx
part of #75 
includes #98 for disabling ripple
Sets up `DropdownMenuItem` for removal.
> feat(MenuItem): add component and global styles

- libs/spark/src/Button.ts
Closes #157 
Fixes some issues found in #127 
Merge will wait until Chromatic can be reviewed.
> feat(Button): update styles

- libs/spark/src/SparkThemeProvider.tsx
> fix: overlapping class name generation with consumers

- CHANGELOG.md
- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
- package.json
* Revise changelog
* Increment version in spark `package.json`
* tag v0.10.0
> chore(release): 0.10.0

- CHANGELOG.md
- libs/spark-icons/CHANGELOG.md
- libs/spark/CHANGELOG.md
Amends previous changelog entries of failed release and merges subsequent fixes.
A new tag has been created
> chore(release): v0.11.1, corrected

- libs/spark/CHANGELOG.md
- libs/spark/src/IconButton.tsx
- libs/spark/src/index.ts
- libs/spark/src/styles/overrides.ts
- libs/spark/stories/documentation-template.tsx
- libs/spark/stories/icon-button.stories.tsx
Resolves #243 with ref-forwarding
Part of #231 with separation of custom classes
Part of #207 with documentation story finished and changelog started
> feat(IconButton): add ref-forwarding & improve signature

- libs/spark/src/Autocomplete.tsx
- libs/spark/src/Avatar.tsx
- libs/spark/src/Button.ts
- libs/spark/src/Checkbox.tsx
- libs/spark/src/Divider.ts
- libs/spark/src/FormControlLabel.ts
- libs/spark/src/FormHelperText.ts
- libs/spark/src/FormLabel.ts
- libs/spark/src/InputBase.tsx
- libs/spark/src/InputLabel.ts
- libs/spark/src/ListItem.ts
- libs/spark/src/ListItemIcon.ts
- libs/spark/src/ListItemText.ts
- libs/spark/src/ListSubheader.ts
- libs/spark/src/Menu.ts
- libs/spark/src/MenuItem.tsx
- libs/spark/src/PaginationItem.ts
- libs/spark/src/Radio.tsx
- libs/spark/src/Select.ts
- libs/spark/src/SvgIcon.tsx
- libs/spark/src/styles/overrides.ts
- libs/spark/src/styles/theme.ts
> chore: two-step theme creation for overrides

- libs/spark/src/NavBar.tsx
> refactor(NavBar): combine statements

- CHANGELOG.md
- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
- libs/spark/stories/avatar.stories.tsx
- libs/spark/stories/banner.stories.tsx
- libs/spark/stories/icon-button.stories.tsx
- libs/spark/stories/section-message.stories.tsx
- libs/spark/stories/switch.stories.tsx
- libs/spark/stories/tab.stories.tsx
- libs/spark/stories/tabs.stories.tsx
- libs/spark/stories/tag.stories.tsx
- libs/spark/stories/typography.stories.tsx
- package.json
- vNext -> v0.12.0
- yyyy-mm-dd -> 2021-09-28
- New vNext entries
- Added "No changes" where applicable
- Pushed tag v0.12.0
- Incremented pkg and workspace versions
> chore(release): v0.12.0

- CHANGELOG.md
- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
- package-lock.json
- package.json
(Planning to add these steps to CONTRIBUTOR guidelines, i'll create a task issue -- #264 )
> chore(release): v0.13.0

- CHANGELOG.md
- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
- package-lock.json
- package.json
> chore(release): v0.13.1

- .github/workflows/npm-publish.yml
> chore(workflow): try alternative for github ref env var

- CONTRIBUTING.md
- README.md
- libs/spark-icons/BUILDER.md
- libs/spark/CHANGELOG.md
- libs/spark/README.md
- libs/spark/src/Checkbox.tsx
- libs/spark/src/Radio.tsx
- libs/spark/src/theme/palette.ts
- libs/spark/stories/autocomplete.stories.tsx
- libs/spark/stories/avatar.stories.tsx
- libs/spark/stories/icon-button.stories.tsx
- libs/spark/stories/menuitem.stories.tsx
- libs/spark/stories/menulist.stories.tsx
- libs/spark/stories/tag.stories.tsx
> chore: replace "Material-UI" with "MUI" and update url's

- CHANGELOG.md
- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
- package-lock.json
- package.json
> chore(release): v0.14.0

- libs/spark/CHANGELOG.md
- libs/spark/src/Button/defaults.ts
> fix(Button): incorrect default height for some variants

- libs/spark/jest.config.js
- libs/spark/jest.setup.ts
- libs/spark/src/Checkbox/Checkbox.spec.tsx
- libs/spark/src/Checkbox/Checkbox.stories.tsx
- libs/spark/src/Checkbox/CheckboxIcon.tsx
- libs/spark/src/Checkbox/defaults.tsx
- libs/spark/src/Radio/Radio.spec.tsx
- libs/spark/src/Radio/RadioIcon.tsx
- libs/spark/src/Radio/defaults.tsx
- libs/spark/tsconfig.json
- libs/spark/tsconfig.spec.json
- package-lock.json
- package.json
Close #339 
reviewable by commit
> test(Checkbox,Radio): ensure logic around checked/indeterminate

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.1

- libs/spark/src/Link/Link.tsx
> fix(Link): default outline on Firefox

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.2

- libs/spark/CHANGELOG.md
- libs/spark/src/theme/overrides.ts
- libs/spark/src/theme/theme.ts
- libs/spark/src/theme/themeAugmentation.ts
- libs/spark/src/theme/unstable_fontFaces.stories.tsx
- libs/spark/src/theme/unstable_fontFaces.ts
- libs/spark/src/theme/unstable_palette.stories.tsx
- libs/spark/src/theme/unstable_palette.ts
- libs/spark/src/theme/unstable_typography.stories.tsx
- libs/spark/src/theme/unstable_typography.ts
Changes unstable preview code prefix and talk. Close #364
> feat(unstable_): change __next__ to unstable_

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.3

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.stories.tsx
- libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.test.tsx
- libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.tsx
- libs/spark/src/Unstable_FormHelperText/index.ts
- libs/spark/src/Unstable_InputAdornment/Unstable_InputAdornment.stories.tsx
- libs/spark/src/index.ts
Part of #350  .
Necessary pre-req for Input / Select / TextField.
> feat(Unstable_FormHelperText): initial implementation

- libs/spark/CHANGELOG.md
> chore(changelog): add entry for `Unstable_Button`

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.4

- libs/spark/CHANGELOG.md
- libs/spark/src/Select/defaults.tsx
> fix(Select): "react" not in scope

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.5

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Button/Unstable_Button.stories.tsx
- libs/spark/src/Unstable_Button/Unstable_Button.tsx
- Specifically targeting when the theme Provider of spark v1 has styling overrides.
> fix(Unstable_Button): override previous theme styles

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.6

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
- [] _(after PR merge)_ Draft new release
> chore(release): v1.0.0-alpha.7

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
Added missing changelog entry from #414
> chore(release): v1.0.0-alpha.8

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Radio/Unstable_Radio.stories.tsx
- libs/spark/src/Unstable_Radio/Unstable_Radio.test.tsx
- libs/spark/src/Unstable_Radio/Unstable_Radio.tsx
- libs/spark/src/Unstable_Radio/Unstable_RadioIcon.tsx
- libs/spark/src/Unstable_Radio/index.ts
- libs/spark/src/index.ts
Part of #349 
Only does the little radio button, not integration with FormControlLabel.
> feat(Unstable_Radio): initial implementation

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_FormControl/Unstable_FormControl.stories.tsx
- libs/spark/src/Unstable_FormControl/Unstable_FormControl.test.tsx
- libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
- libs/spark/src/Unstable_FormControl/formControlState.ts
- libs/spark/src/Unstable_FormControl/index.ts
- libs/spark/src/Unstable_FormControl/useFormControl.ts
- libs/spark/src/index.ts
Pretty straight forward, it's a logical/functional component rather than one with an appearance.
> feat(Unstable_FormControl): initial implementation

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.10

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_AvatarButton/Unstable_AvatarButton.stories.tsx
- libs/spark/src/Unstable_AvatarButton/Unstable_AvatarButton.tsx
- Add the size attribute to the `Unstable_AvatarButton` with medium and large options.
> feat(Unstable_AvatarButton): add  size prop

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.11

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Input/Unstable_Input.tsx
Obvious in the story, just missed initially.
> fix(Unstable_Input): bad margin under STP

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Switch/Unstable_Switch.stories.tsx
- libs/spark/src/Unstable_Switch/Unstable_Switch.test.tsx
- libs/spark/src/Unstable_Switch/Unstable_Switch.tsx
- libs/spark/src/Unstable_Switch/index.ts
- libs/spark/src/index.ts
> feat(Unstable_Switch): initial implementation

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_SwitchField/Unstable_SwitchField.stories.tsx
- libs/spark/src/Unstable_SwitchField/Unstable_SwitchField.test.tsx
- libs/spark/src/Unstable_SwitchField/Unstable_SwitchField.tsx
- libs/spark/src/Unstable_SwitchField/index.ts
- libs/spark/src/index.ts
- libs/spark/stories/decorators.tsx
> feat(Unstable_SwitchField): initial implementation

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.12

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.13

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_ContentGroup/Unstable_ContentGroup.stories.tsx
- libs/spark/src/Unstable_ContentGroup/Unstable_ContentGroup.test.tsx
- libs/spark/src/Unstable_ContentGroup/Unstable_ContentGroup.tsx
- libs/spark/src/Unstable_ContentGroup/index.ts
- libs/spark/src/index.ts
Extracts this very useful pattern of composition from Unstable List Item and into its own component. I called it "Content Group" because it's usefulness is in grouping different elements with varying content: text (primary and accessory), icons, actions, maybe even images, etc.
In a followup PR, I will use this component in Unstable List Item and it will ripple through components that inherit from it. It will involved breaking changes.
> feat(Unstable_ContentGroup): initial implementation

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_CheckboxListItem/Unstable_CheckboxListItem.stories.tsx
- libs/spark/src/Unstable_CheckboxListItem/Unstable_CheckboxListItem.tsx
- libs/spark/src/Unstable_CheckboxMenuItem/Unstable_CheckboxMenuItem.stories.tsx
- libs/spark/src/Unstable_List/Unstable_List.stories.tsx
- libs/spark/src/Unstable_ListItem/Unstable_ListItem.stories.tsx
- libs/spark/src/Unstable_ListItem/Unstable_ListItem.tsx
- libs/spark/src/Unstable_MenuItem/Unstable_MenuItem.stories.tsx
Based on #550 
Breaking change.
Replace complex props signature with embedded `Unstable_ContentGroup` instance. Forced on consumers since the pattern is so common for basic usage.
> feat(Unstable_ListItem)!: use Content Group

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0-alpha.14

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v1.0.0

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.1

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.2

- libs/spark/src/Unstable_Tag/Unstable_Tag.tsx
Figma updated without design change issue filed
> feat(Unstable_Tag): change background colors for subtle variant

- libs/spark/CHANGELOG.md
- libs/spark/src/theme/unstable_palette.stories.tsx
- libs/spark/src/theme/unstable_palette.ts
> feat(theme): add overlay to background palette

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Menu/Unstable_Menu.tsx
- libs/spark/src/Unstable_ModalDialog/Unstable_ModalDialog.tsx
- libs/spark/src/Unstable_Paper/Unstable_Paper.stories.tsx
- libs/spark/src/Unstable_Paper/Unstable_Paper.tsx
- libs/spark/src/Unstable_Select/Unstable_Select.tsx
- libs/spark/src/theme/initialTheme.ts
- libs/spark/stories/decorators.tsx
Base: #568 
Now that elevations are formalized, Paper and composing components are re-api'd with them.
> feat(Paper)!: change elevation values to match theme

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_SvgIcon/Unstable_SvgIcon.tsx
> feat(SvgIcon): make styles static

- libs/spark/CHANGELOG.md
Adds changelog entry forgotten in #567
> chore: add forgotten changelog of #567

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Typography/Unstable_Typography.stories.tsx
- libs/spark/src/Unstable_Typography/Unstable_Typography.tsx
> feat(Typography): make styles static

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Typography/Unstable_Typography.tsx
Part of #572 
Improvement of #575 following same reasoning of #577
> feat(Typography)!: privatize non-slot classes

- libs/spark/.storybook/preview.js
- libs/spark/CHANGELOG.md
- libs/spark/src/CssBaseline/CssBaseline.ts
Based on this discussion: https://github.com/mui/material-ui/issues/16367 which links other sources.
Also a followup to #402 with an effective solution (previous one failed).
> feat(spark): support reduced motion

- libs/spark/src/internal/Unstable_Alert.tsx
This way the classes object will always be defined
> feat(Alert): well-define classes

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.tsx
> feat(SectionMessage): props-static styles

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Banner/Unstable_Banner.tsx
> feat(Banner): props-static styles

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Button/Unstable_Button.tsx
> feat(Button): props-static styles

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
> feat(IconButton): props-static styles

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Avatar/Unstable_Avatar.tsx
> feat(Avatar): props-static styles

- libs/spark/src/Unstable_AvatarButton/Unstable_AvatarButton.tsx
> refactor(AvatarButton): use withClasses pattern

- libs/spark/src/Unstable_Checkbox/Unstable_Checkbox.tsx
> refactor(Checkbox): withClasses pattern

- libs/spark/src/Unstable_CheckboxField/Unstable_CheckboxField.tsx
> refactor(CheckboxField): withClasses pattern

- libs/spark/src/Unstable_CheckboxListItem/Unstable_CheckboxListItem.tsx
> refactor(CheckboxListItem): withClasses pattern

- libs/spark/src/Unstable_CheckboxMenuItem/Unstable_CheckboxMenuItem.tsx
> refactor(CheckboxMenuItem): withClasses pattern

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_ContentGroup/Unstable_ContentGroup.tsx
> feat(ContentGroup): privatize props classes; withClasses pattern

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Divider/Unstable_Divider.tsx
> feat(Divider): remove props classes; adopt withClasses

- libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
> refactor(FormControl): adopt withClasses pattern

- libs/spark/src/Unstable_FormControlLabel/Unstable_FormControlLabel.tsx
> refactor(FormControlLabel): adopt withClasses pattern

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.3

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_SwitchField/Unstable_SwitchField.tsx
> feat(SwitchField): increase label font weight

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.4

- libs/spark/CHANGELOG.md
- libs/spark/package.json
- libs/spark/src/Unstable_ToastsProvider/Unstable_ToastsContext.ts
- libs/spark/src/Unstable_ToastsProvider/Unstable_ToastsProvider.stories.tsx
- libs/spark/src/Unstable_ToastsProvider/Unstable_ToastsProvider.test.tsx
- libs/spark/src/Unstable_ToastsProvider/Unstable_ToastsProvider.tsx
- libs/spark/src/Unstable_ToastsProvider/index.ts
- libs/spark/src/index.ts
- package-lock.json
- package.json
Closes #624 
Better wrapper around [Notistack v3](https://notistack.com/getting-started), which has a really poor API. Too bad. Anyway, this is fairly close to [MUI v5 Lab's upcoming implementation](https://github.com/mui/material-ui/pull/31991).
> feat(ToastsProvider): initial implementation

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.5

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Tabs/Unstable_Tabs.tsx
- libs/spark/src/Unstable_Tabs/Unstable_TabsContext.ts
- libs/spark/src/Unstable_TabsList/Unstable_TabsList.tsx
Discovered when trying to use them in PW.
> fix(Tabs): missing React imports

- libs/spark/CHANGELOG.md
- libs/spark/src/DropdownMenu/DropdownMenu.test.tsx
- libs/spark/src/DropdownMenu/DropdownMenu.tsx
- libs/spark/src/Unstable_Menu/Unstable_Menu.tsx
Discovered when trying to use the pattern in PW. The test is mostly for ts-checking, rather than rendering ability.
> fix(Menu): incompatibility with DropdownMenu as override component

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.6

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Switch/Unstable_Switch.tsx
> styles(switch): improve thumb position when large

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_AvatarButton/Unstable_AvatarButton.tsx
- libs/spark/src/Unstable_Button/Unstable_Button.tsx
- libs/spark/src/Unstable_ContentGroup/Unstable_ContentGroup.stories.tsx
- libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
- libs/spark/src/Unstable_Input/Unstable_Input.tsx
- libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.tsx
- libs/spark/src/Unstable_Tab/Unstable_Tab.tsx
- libs/spark/src/Unstable_Tag/Unstable_Tag.tsx
- libs/spark/src/theme/initialTheme.ts
- libs/spark/src/theme/theme.ts
- libs/spark/src/theme/themeAugmentation.ts
- libs/spark/src/theme/unstable_borders.stories.tsx
- libs/spark/src/theme/unstable_borders.ts
- libs/spark/src/theme/unstable_radius.stories.tsx
> feat(theme): add "borders"

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Menu/Unstable_Menu.tsx
- libs/spark/src/Unstable_ModalDialog/Unstable_ModalDialog.tsx
- libs/spark/src/Unstable_Paper/Unstable_Paper.stories.tsx
- libs/spark/src/Unstable_Paper/Unstable_Paper.tsx
- libs/spark/src/Unstable_Select/Unstable_Select.tsx
- libs/spark/src/theme/themeAugmentation.ts
- libs/spark/src/theme/unstable_borders.ts
- libs/spark/src/theme/unstable_radii.ts
- libs/spark/src/theme/unstable_shadows.ts
Made Paper more analogous to what "Box" should have been, maybe it'll become that one day, idk.
Fixed various props defaults related to Paper in consuming components.
> feat(Paper)!: re-implement

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Card/Unstable_Card.stories.tsx
- libs/spark/src/Unstable_Card/Unstable_Card.test.tsx
- libs/spark/src/Unstable_Card/Unstable_Card.tsx
- libs/spark/src/Unstable_Card/index.ts
- libs/spark/src/index.ts
> feat(Card): initial implementation

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_ListItem/Unstable_ListItem.tsx
> style(ListItem): remove browser-default outline on focus-visible

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
- libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.stories.tsx
- libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.tsx
- libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.stories.tsx
- libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx
- libs/spark/src/Unstable_Input/Unstable_Input.stories.tsx
- libs/spark/src/Unstable_Input/Unstable_Input.tsx
- libs/spark/src/Unstable_InputAdornment/Unstable_InputAdornment.stories.tsx
- libs/spark/src/Unstable_InputAdornment/Unstable_InputAdornment.tsx
- libs/spark/src/Unstable_Select/Unstable_Select.stories.tsx
- libs/spark/src/Unstable_Select/Unstable_Select.tsx
- libs/spark/src/Unstable_TextField/Unstable_TextField.stories.tsx
- libs/spark/src/Unstable_TextField/Unstable_TextField.tsx
> feat(spark): add size prop to input components

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.7

- libs/spark/CHANGELOG.md
- libs/spark/src/SparkThemeProvider/SparkThemeProvider.tsx
This reverts commit 0dce0eb210adce71d283a8bf10ddd7f2314fb7cb.
This broke our consumer's app styling in a severe way.
> Revert "feat(SparkThemeProvider): inject styles last (#632)"

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Banner/Unstable_Banner.tsx
- libs/spark/src/Unstable_Button/Unstable_Button.tsx
- libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
- libs/spark/src/Unstable_ModalDialog/Unstable_ModalDialog.tsx
- libs/spark/src/Unstable_ModalDialogTitle/Unstable_ModalDialogTitle.tsx
- libs/spark/src/Unstable_Toast/Unstable_Toast.tsx
> style(Button): correct height and text alignment

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.8

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.9

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_CheckboxGroupField/Unstable_CheckboxGroupField.stories.tsx
- libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
- libs/spark/src/Unstable_FormGroup/Unstable_FormGroup.tsx
- libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx
- libs/spark/src/Unstable_RadioGroupField/Unstable_RadioGroupField.stories.tsx
Related to #660 . There were some similar problems plaguing the Form*** component family that can be summed up similarly.
> fix(FormControl): `fullWidth` not working

- libs/spark/src/Unstable_Avatar/Unstable_Avatar.tsx
- libs/spark/src/Unstable_Banner/Unstable_Banner.tsx
- libs/spark/src/Unstable_Card/Unstable_Card.tsx
- libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.tsx
Carried over from Prenda World exploration to Banner, Card, Section Message
> style: add some mobile styles

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Button/Unstable_Button.tsx
Just riffing until design spec is finalized.
> style(Button): improve styles when `color="inverse"`

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_ToastsContext/Unstable_ToastsContext.d.ts
- libs/spark/src/useToasts_unstable/useToasts_unstable.ts
Default placement has changed to "bottom-center". Added some ways to send toasts with a severity without an additional options object that makes calls stick out a lot.
> feat(Toast): change default placement; add convenience enqueue

- libs/spark-icons/CHANGELOG.md
- libs/spark/CHANGELOG.md
> chore: fix last version date

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Link/Unstable_Link.stories.tsx
- libs/spark/src/Unstable_Link/Unstable_Link.tsx
Consumers will want the text of the link to be inline with text on the line elsewhere.
> fix(Link): vertical alignment when `component="button"`

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.tsx
- libs/spark/src/Unstable_InputAdornment/Unstable_InputAdornment.tsx
Recent design change. Already applied to Select in #661 and Autocomplete in #668
> style(InputAdornment): increase font size when `size="small"`

- libs/spark/CHANGELOG.md
- libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.stories.tsx
- libs/spark/src/Unstable_CheckboxGroupField/Unstable_CheckboxGroupField.stories.tsx
- libs/spark/src/Unstable_FormControl/Unstable_FormControl.stories.tsx
- libs/spark/stories/decorators.tsx
> chore: add some stories; amend changelog; remove comment

- libs/spark/src/useFormControl_unstable/useFormControl_unstable.ts
> fix(useFormControl): remove mistakenly added `row` value

- libs/spark/CHANGELOG.md
- libs/spark/src/createSvgIcon_unstable/createSvgIcon_unstable.test.tsx
- libs/spark/src/createSvgIcon_unstable/createSvgIcon_unstable.tsx
- libs/spark/src/createSvgIcon_unstable/index.ts
- libs/spark/src/unstable_createSvgIcon.tsx
- deprecate unstable_createSvgIcon in favor of createSvgIcon_unstable
- new name for old util, no changes
- add tests
> feat(createSvgIcon): initial implementation

- libs/spark/CHANGELOG.md
- libs/spark/src/useMediaQuery_unstable/index.ts
- libs/spark/src/useMediaQuery_unstable/useMediaQuery_unstable.test.ts
- libs/spark/src/useMediaQuery_unstable/useMediaQuery_unstable.ts
- libs/spark/src/useTheme_unstable/index.ts
- libs/spark/src/useTheme_unstable/useTheme_unstable.test.ts
- libs/spark/src/useTheme_unstable/useTheme_unstable.ts
- package-lock.json
- package.json
> feat: implement useMediaQuery_unstable, useTheme_unstable

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.13

- libs/spark/CHANGELOG.md
- libs/spark/src/TopBar_unstable/TopBar_unstable.spec.tsx
- libs/spark/src/TopBar_unstable/TopBar_unstable.stories.tsx
- libs/spark/src/TopBar_unstable/TopBar_unstable.tsx
- libs/spark/src/TopBar_unstable/index.ts
- libs/spark/src/index.ts
> feat(TopBar): initial implementation (unstable)

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.14

- libs/spark/CHANGELOG.md
- libs/spark/src/Drawer_unstable/Drawer_unstable.spec.tsx
- libs/spark/src/Drawer_unstable/Drawer_unstable.tsx
- libs/spark/src/Drawer_unstable/index.ts
- libs/spark/src/SideBarContext_unstable/SideBarContext_unstable.ts
- libs/spark/src/SideBarContext_unstable/index.ts
- libs/spark/src/SideBarDrawer_unstable/SideBarDrawer_unstable.spec.tsx
- libs/spark/src/SideBarDrawer_unstable/SideBarDrawer_unstable.tsx
- libs/spark/src/SideBarDrawer_unstable/index.ts
- libs/spark/src/SideBarListItem_unstable/SideBarListItem_unstable.spec.tsx
- libs/spark/src/SideBarListItem_unstable/SideBarListItem_unstable.tsx
- libs/spark/src/SideBarListItem_unstable/index.ts
- libs/spark/src/SideBarListSubheader_unstable/SideBarListSubheader_unstable.spec.tsx
- libs/spark/src/SideBarListSubheader_unstable/SideBarListSubheader_unstable.ts
- libs/spark/src/SideBarListSubheader_unstable/index.ts
- libs/spark/src/SideBarList_unstable/SideBarList_unstable.spec.tsx
- libs/spark/src/SideBarList_unstable/SideBarList_unstable.tsx
- libs/spark/src/SideBarList_unstable/index.ts
- libs/spark/src/SideBarProvider_unstable/SideBarProvider_unstable.spec.tsx
- libs/spark/src/SideBarProvider_unstable/SideBarProvider_unstable.stories.tsx
- libs/spark/src/SideBarProvider_unstable/SideBarProvider_unstable.tsx
- libs/spark/src/SideBarProvider_unstable/index.ts
- libs/spark/src/index.ts
- libs/spark/src/useSideBarTrigger_unstable/index.ts
- libs/spark/src/useSideBarTrigger_unstable/useSideBarTrigger_unstable.ts
- libs/spark/src/useSideBar_unstable/index.ts
- libs/spark/src/useSideBar_unstable/useSideBar_unstable.ts
> feat(SideBar): initial implementation (unstable)

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.15

- libs/spark/CHANGELOG.md
- libs/spark/src/SideBarDrawer_unstable/SideBarDrawer_unstable.tsx
> fix(SideBarDrawer): missing React import

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.16

- libs/spark/CHANGELOG.md
- libs/spark/src/alpha/SideBarListItem/SideBarListItem.tsx
- libs/spark/src/alpha/SideBarListSubheader/SideBarListSubheader.ts
- libs/spark/src/alpha/SideBarProvider/SideBarProvider.stories.tsx
- libs/spark/src/alpha/theme/typography.ts
Previously didn't match design spec
> style(SideBar): change typography, reduce padding

- libs/spark/CHANGELOG.md
- libs/spark/src/alpha/Menu/Menu.tsx
> style(Menu): unset v1 list styles

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.17

- libs/spark/CHANGELOG.md
- libs/spark/src/Breadcrumbs/Breadcrumbs.tsx
- libs/spark/src/alpha/Breadcrumb/Breadcrumb.stories.tsx
- libs/spark/src/alpha/Breadcrumb/Breadcrumb.test.tsx
- libs/spark/src/alpha/Breadcrumb/Breadcrumb.tsx
- libs/spark/src/alpha/Breadcrumb/index.ts
- libs/spark/src/alpha/Breadcrumbs/Breadcrumbs.stories.tsx
- libs/spark/src/alpha/Breadcrumbs/Breadcrumbs.test.tsx
- libs/spark/src/alpha/Breadcrumbs/Breadcrumbs.tsx
- libs/spark/src/alpha/Breadcrumbs/index.ts
- libs/spark/src/alpha/index.ts
Closes #445 
See [spec](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/components?node-id=949-0)
> feat: add Breadcrumb, Breadcrumbs (alpha)

- libs/spark-icons/CHANGELOG.md
- libs/spark-icons/package.json
- libs/spark/CHANGELOG.md
- libs/spark/package.json
> chore(release): v2.0.0-alpha.18

- .github/workflows/chromatic.yml
- libs/storybook-host/.storybook/main.ts
- libs/storybook-host/project.json
- nx.json
- package-lock.json
- package.json
- packages/tokens/.babelrc
- packages/tokens/.eslintrc.json
- packages/tokens/.storybook/main.ts
- packages/tokens/README.md
- packages/tokens/jest.config.ts
- packages/tokens/package.json
- packages/tokens/project.json
- packages/tokens/src/index.ts
- packages/tokens/src/lib/tokens.spec.tsx
- packages/tokens/src/lib/tokens.stories.tsx
- packages/tokens/src/lib/tokens.tsx
- packages/tokens/tsconfig.json
- packages/tokens/tsconfig.lib.json
- packages/tokens/tsconfig.spec.json
- packages/tokens/tsconfig.storybook.json
- packages/tokens/vite.config.ts
- tsconfig.base.json
> chore: initialize package for tokens

- packages/tokens/src/index.ts
- packages/tokens/src/skin-tone.stories.tsx
- packages/tokens/src/skin-tone.ts
Adds global tokens and palettes for skin tones.
> feat(tokens): add skin tone tokens

- package-lock.json
- package.json
- packages/tokens/.storybook/components.tsx
- packages/tokens/package.json
- packages/tokens/src/index.ts
- packages/tokens/src/radius.stories.tsx
- packages/tokens/src/radius.ts
Add global tokens and palette for radius
> feat(tokens): add radius

- packages/tokens/src/background-color.stories.tsx
- packages/tokens/src/background-color.ts
- packages/tokens/src/index.ts
Add alias tokens and palette for background color.
> feat(tokens): add background color

- packages/tokens/src/index.ts
- packages/tokens/src/text-color.stories.tsx
- packages/tokens/src/text-color.ts
Add alias tokens and palette for text color.
> feat(tokens): add text color

- packages/tokens/.storybook/components.tsx
- packages/tokens/src/box-shadow.stories.tsx
- packages/tokens/src/box-shadow.ts
- packages/tokens/src/index.ts
Add composite tokens and palettes for box shadow
> feat(tokens): add box shadow

- packages/tokens/.storybook/components.tsx
- packages/tokens/src/border.stories.tsx
- packages/tokens/src/border.ts
- packages/tokens/src/index.ts
Add composite tokens and palettes for border.
> feat(tokens): add border

- packages/tokens/.storybook/preview-head.html
- packages/tokens/src/font-family.stories.tsx
- packages/tokens/src/font-family.ts
- packages/tokens/src/font-feature-settings.ts
- packages/tokens/src/font-size.stories.tsx
- packages/tokens/src/font-size.ts
- packages/tokens/src/index.ts
Add global tokens for font-family, font-feature-settings, font-size.
Loads font files from google for Storybook. The font-feature-settings don't actually work (thus don't have stories), because the files that google provides do not come with font-features.
> feat(tokens): add font-family, font-feature-settings, font-size

- packages/tokens/src/index.ts
- packages/tokens/src/typography.stories.tsx
- packages/tokens/src/typography.ts
Add composite tokens and palettes for typography.
> feat(tokens): add typography

- packages/tokens/.storybook/preview-head.html
- Include Roboto Mono, not Source Code Pro
- Include single embed structure with all fonts in one stylesheet
> chore: fix fonts embedded in storybook

- packages/dataviz/.storybook/main.ts
- packages/dataviz/.storybook/preview-head.html
- packages/dataviz/decorators/OutlineOriginCenter.stories.tsx
- packages/dataviz/decorators/OutlineOriginCenter.tsx
- packages/dataviz/decorators/OutlineOriginTopLeft.stories.tsx
- packages/dataviz/decorators/OutlineOriginTopLeft.tsx
- packages/dataviz/decorators/index.ts
- packages/dataviz/examples/report-card/empowerment-metric/DualLinearGauge.stories.tsx
- packages/dataviz/examples/report-card/empowerment-metric/DualRadialGauge.stories.tsx
- packages/dataviz/examples/report-card/empowerment-metric/SegmentedCircularGauge.stories.tsx
- packages/dataviz/examples/report-card/mastery-goal/DualCircularGauge.stories.tsx
- packages/dataviz/examples/report-card/portfolio/BarChart.stories.tsx
- packages/dataviz/src/ResponsiveChart/useResponsiveChart.ts
> chore(dataviz): add some storybook decorator utils and examples dir

- packages/dataviz/.eslintrc.json
- packages/dataviz/src/Bar/Bar.tsx
- packages/dataviz/src/BarScale/BarScale.tsx
- packages/dataviz/src/BarUnits/BarUnits.tsx
- packages/dataviz/src/LinearScale/LinearScale.tsx
- packages/dataviz/src/LinearUnits/LinearUnits.tsx
- packages/dataviz/src/RadialBar/RadialBar.tsx
- packages/dataviz/src/RadialBarScale/RadialBarScale.tsx
- packages/dataviz/src/RadialBarSegments/RadialBarSegments.tsx
- packages/dataviz/src/RadialBarUnits/RadialBarUnits.tsx
> fix(dataviz): some components can't be used as JSX components
