CHANGELOG.md
apps/spark-e2e/CHANGELOG.md
libs/spark/CHANGELOG.md
libs/spark/package.json
nx.json
package-lock.json
package.json
workspace.json

Closes #65. 
Adds missing tag for `spark-0.7.3` as noted in #72.
- Amends the missing CHANGELOG entry as well, with suitable scope.
Adds initial workspace tag `v0.7.3` on same commit as `spark-0.7.3` tag
Installs `@jscutlery/semver` for the entire workspace
- _NOTE:_ Conventional Commits is _not_ enforced as a `commit-msg` hook. Contributors are free to describe commits however they like. It is the responsibility of the maintainers that the squash-and-merge commit abides by Conventional Commits.
Runs release generator to bump workspace and projects, keeping versions synced.
```bash
npx nx run workspace:version --sync-versions true
git push --follow-tags origin <branch-name>
```
Amends CHANGELOG's to improve feature descriptions, scopes.
-----
Here's the commit msg that GitHub suggests on …

chore(release): v0.8.0, version workspace, sync projects, amend past

---

.github/workflows/npm-publish.yml

The action didn't trigger when I released an existing tag. I'm not sure why, hopefully this change fixes that.
I added `workflow_dispatch` so I can manually trigger the action for the existing release

chore(workflow): change published to released

---

libs/spark/src/Checkbox.tsx
libs/spark/src/Radio.tsx
libs/spark/src/SvgIcon.tsx
libs/spark/src/index.ts
libs/spark/src/theme/theme.ts

part of #75 
This new customization will replace the current `Icon` -- will be removed in another PR (since that's just a custom SvgIcon. I implemented the `contrast` prop by changing the `opacity` CSS property instead of switching to the `...LowContrast` version of the text colors. This was to simplify implementation. From my assessment, with something so simple as icons, it produces the exact same result.
This is also a prerequisite for #73

feat(SvgIcon): add global styles and props

---

libs/spark/src/Button.tsx
libs/spark/src/ButtonBase.ts
libs/spark/src/theme/theme.ts

part of #75 
The default props are especially important as they should disable the "ripple" across all components. Once this and other outstanding PRs are merged, we can remove existing redundancies.

feat(ButtonBase): add global styles and props

---

libs/spark/src/theme/palette.ts

Part of #103 
The color value names in Figma are long and tailored for exporting as lone constants, not as part of a palette object. They also don't reflect how they'll be organized in the palette. Now that we're importing what's basically the `palette` object for use in our style overrides, this is a noticeable pain point.
Similar to how `shadows.ts` exports a single `shadows` object, I've created `palette.ts` to export a single `palette` object.
This PR just introduces the new format for dev feedback on names and organization within the object. My goals were
- integrate more closely with the [default theme](https://material-ui.com/customization/default-theme/?expand-path=$.palette)
- eliminate value repetition
- eliminate re-specification of default Mui values -- the `createMuiTheme` …

feat(palette): initial implementation, simplified names

---

libs/spark/src/fonts.d.ts

Was a relic of an old font import attempt, definitely not needed now.

chore: remove fonts.d.ts

---

libs/spark/src/Dropdown.tsx
libs/spark/src/Menu.ts

Our `Menu`'s are spec'd to be 8px offset from their anchor. My previous method of adjusting the inset of the entire popover was naive -- that element is inset to the screen, not an area. A top margin is better. It has to be applied conditionally by the consuming scenario, so I defined a utility class. Ideally we could define something that covers all scenarios, but I haven't figured that yet.

refactor(Menu): add utility class for margin top

---

libs/spark/src/InputBase.tsx
libs/spark/stories/input.stories.tsx

Renames `SparkInput-success` to `Spark-success` because 1) it's defined on `InputBase` now 2) it will extend to `Select` and other components that inherit from `InputBase` and 3) mirrors `Mui-error`.
Also switches from padding the root to the `input` element. This is necessary from an upcoming `Select` implementation.

refactor(InputBase): rename success class, switch padded element

---

libs/spark/src/Dropdown.tsx
libs/spark/src/Select.ts
libs/spark/src/icons/line/ChevronDown.js
libs/spark/src/styles/overrides.ts
libs/spark/src/styles/props.ts
libs/spark/stories/select.stories.tsx

~Draft until required #121 and #122 are merged~
Closes #123
Implementing placeholder text and its styling is fairly tricky. It's not even really part of normal HTML. You have to give a default, disabled value option (`value=""`), an empty string as your initial state, and let Mui know you want to display that default value.
Storybook was also wigging out on controlling the `value` state by itself, so I had to add a basic hook for that.
The styling for "Placeholder" text is dynamic unfortunately, because it's not a placeholder like I said, and I couldn't write a style rule like `input[value=""] + & { }` because the `input` element comes _after_ the actually displayed `div`, and CSS doesn't have a "previous sibling" selector, or previous in general. If y'all have a suggestion that doesn't …

feat(Select): initial implementation

---

.eslintrc.json
jest.config.js
libs/spark-icons/.babelrc
libs/spark-icons/.eslintrc.json
libs/spark-icons/README.md
libs/spark-icons/jest.config.js
libs/spark-icons/package.json
libs/spark-icons/tsconfig.json
libs/spark-icons/tsconfig.lib.json
libs/spark-icons/tsconfig.spec.json
nx.json
tsconfig.base.json
workspace.json

This is the first of four PRs that will make up an address to #73. They're separated primarily to make each sensibly reviewable, and also for respective merge commits to paint a better picture. Each PR will be marked as Draft until the previous is merged and the next can be rebased off `main`. You can effectively review each PR by commit.
**1. Project generation (this PR)**
2. Copying of icon utility scripts from Mui & Modification for our use case (#133)
3. Removal of icons from @prenda/spark & Specific generation and replacement of depended-on icons (#134)
4. Addition of all icons in @prenda/spark-icons (#135)
I corrected the `"npmScope"` listed in `nx.json` from `"prenda-spark"` to `"prenda"` (no "@" needed, see @nrwl/nx's setup).
Generated a new NX project, namely a react component …

chore(nx): generate new project, spark-icons (@prenda/spark-icons)

---

.eslintignore
.prettierignore
libs/spark/src/Button.tsx
libs/spark/src/ButtonBase.ts
libs/spark/stories/button.stories.tsx

Part of #101 
- _Does not update the variant names to the new values_
- Adds `:active` styling
- Updates default values.
- Expands the stories to showcase all combinations of the Button's props.

feat(Button): update stylings

---

libs/spark/src/IconButton.tsx
libs/spark/stories/icon-button.stories.tsx

Part of #101
- Does not update the variant names to the new values
- Adds :active styling
- Updates default values.
- Expands the stories to showcase all combinations of the Button's props.

feat(IconButton): update stylings

---

libs/spark/src/FormHelperText.ts
libs/spark/src/FormLabel.ts
libs/spark/src/Input.tsx
libs/spark/src/InputBase.tsx
libs/spark/src/InputLabel.ts
libs/spark/src/PaginationItem.ts
libs/spark/src/Select.ts
libs/spark/src/TextField.ts
libs/spark/src/styles/overrides.ts
libs/spark/src/styles/props.ts
libs/spark/stories/select.stories.tsx
libs/spark/stories/text-field.stories.tsx

Closes #100 
Modifies existing overrides to work in the context of `TextField`. This component is meant as the catch-all combination for `FormLabel, InputLabel, FormHelperText, Input, Select`.
The only failing I had was the `disabled` styling of the Placeholder `TextField select`. The font color is not as light as it should be. But due to the same issues I had in Select's introduction, targeting when the input value is an empty string (i.e. displays the placeholder), I couldn't decrease the opacity or change the font color specifically when disabled -- a dynamic rule didnt work under `{ root: { '&#disabled': { color: (props) => res } } }`.
But it's small and acceptable.

feat(TextField): add theme-level style overrides

---

.github/workflows/chromatic.yml

We're close to our snapshot limit as a Free org in chromatic (4500 out of 5000). Chromatic provided default config runs on every push, but our workflow only requires it to run on reviewable PR's and their updates. I implemented an attempt at the goal, which I researched [here](https://github.community/t/dont-run-actions-on-draft-pull-requests/16817).

chore(ci): reduce chromatic workflow runs

---

libs/spark-icons/defaults/babel.config.js
libs/spark-icons/package.json
libs/spark-icons/scripts/copy-files.js
libs/spark-icons/scripts/create-typings.js
libs/spark/package.json
package-lock.json
package.json

Followup to #135
Closes #138 
Using Nx, `nx run spark-icons:build` produces a tree-shakable bundle, but does not produce a bundle that's ideal for path imports and use with non-tree-shaking bundlers, like Meteor.
The resolution is to again copy and modify what Mui does.
The result is that `@prenda/spark-icons` should now be built from the command `npm run build:icons` issued at the repo root. The build output is sent to `dist/libs/spark-icons-alt` since the Nx build currently occupies the `dist/libs/spark-icons` path.
`> nx run spark-icons:build` produces _n_ TS declaration files BUT _1_ file for each bundle type
vs.
`> npm run icons:build` produces _n_ TS declaration files AND _n_ files

feat(spark-icons): build to be path-import friendly without tree-shaking

---

libs/spark/package.json
libs/spark/src/Select.ts
libs/spark/src/internal/ChevronDown.tsx
libs/spark/src/utils/createSvgIcon.tsx
workspace.json

Closes #161 
Internalizes the single icon from `@prenda/spark-icons` that's used by `@prenda/spark`. Thus we can eliminate the peerDep. Benefit of Nx not requiring us to build Spark Icons before Spark.
The second commit also fixes mismatches between externals and peerDeps.

chore(spark): internalize icons

---

libs/spark/src/ListItem.ts
libs/spark/src/MenuItem.tsx
libs/spark/src/styles/overrides.ts

There were some warning that appeared whenever the spark test suite ran. The disabled class isn't defined for MenuItem, but ListItem -- which MenuItem extends.

feat(ListItem): transfer disabled class style overrides from MenuItem

---

.github/workflows/npm-publish.yml

We should be able to use the same "automation" token that's currently setup.
Builds using the custom babel config.
Notifies the slack channel separately from `@prenda/spark` publish. Maybe another reason to create a "webhooks" channel.

chore(gha): add steps to publish @prenda/spark-icons

---

libs/spark/src/Box.ts
libs/spark/src/Button.ts
libs/spark/src/ButtonBase.ts
libs/spark/src/Card.tsx
libs/spark/src/CardActions.tsx
libs/spark/src/CardContent.tsx
libs/spark/src/CardMedia.ts
libs/spark/src/Checkbox.tsx
libs/spark/src/FormControl.ts
libs/spark/src/FormControlLabel.ts
libs/spark/src/FormGroup.ts
libs/spark/src/FormHelperText.ts
libs/spark/src/FormLabel.ts
libs/spark/src/Input.tsx
libs/spark/src/InputBase.tsx
libs/spark/src/InputLabel.ts
libs/spark/src/ListItem.ts
libs/spark/src/Menu.ts
libs/spark/src/Pagination.ts
libs/spark/src/PaginationItem.ts
libs/spark/src/Radio.tsx
libs/spark/src/RadioGroup.ts
libs/spark/src/Select.ts
libs/spark/src/TextField.ts
libs/spark/src/Toolbar.ts
libs/spark/src/index.ts

Resolves #178 by removing `export * from '@material-ui/core'` and replacing it with specific exports of just components the Prenda library styles or uses in Storybook examples.

fix!: replace wildcard re-export of Mui with limited, named re-exports

---

libs/spark/README.md
libs/spark/src/Typography.tsx
libs/spark/stories/typography.stories.tsx

Update Typography font-weights and storybook to match Figma specifications [here](https://www.figma.com/file/KTeHk612CXRDK2nrOI1nei/Spark-Typography?node-id=2%3A2)
Resolves #33

feat(spark typography): match Figma font weights

---

libs/spark/src/Card.tsx
libs/spark/src/Menu.ts
libs/spark/src/styles/shadows.ts
libs/spark/stories/card.stories.tsx

Translates Spark Design Elevations E100 to E500 to `theme.shadows[1 ... 5]` and sets `theme.shadows[5 ... 24]` to be equivalent to `theme.shadows[5]`, the highest elevation shadow.
Replaces Mui's utility with one that fits our exact need.
Adjusts components that use elevations (Card and Menu) to their new prescribed elevations.
Unfortunately, it was not possible to customize the shadows object to have our elevations correspond to keys like `shadows[100]` etc. This was because the `type Shadows` cannot be overridden with TS module augmentation. Other, more cruder overriding methods still couldn't satisfy dependents, like `ThemeOptions` or `Theme`, to play well with a custom type.

feat(theme): adjust shadows to new elevations spec

---

libs/spark/CHANGELOG.md
libs/spark/src/Avatar.tsx
libs/spark/src/index.ts
libs/spark/src/styles/overrides.ts
libs/spark/stories/avatar.stories.tsx
libs/spark/stories/navbar.stories.tsx

Closes #52 
- Implements a custom classes CSS API like `Typography`, that is style-able with customers using the standard utilities (`withStyles`, etc.).
- See #200 for details
- Implements 4 sizes across 3 content types
- Content types are intentionally not variants, they have intertwining behavior, see Mui docs.
- Adds documentation story linking out to Mui and highlighting differences.
- Adds changelog story
I'm imagining both Documentation and Changelog stories to become standard for all components.

feat(Avatar): initial implementation

---

libs/spark/CHANGELOG.md
libs/spark/src/Button.ts

Closes #202 .
- Removed custom line height for small button and adjusted padding accordingly
- Removed padding set per variant and sets it on `root` instead.
- Corrected x-dimension padding to be 14px accounting for 2px border width.
In the effort to reduce comments and reducing where code take mental effort to compare to Figma values, I left basic arithmetic expression in the `pxToRem` function calls. The reasoning is that designers use inside borders on the main element, so the measurement displayed from the label edges to the buttons edges aren't a reflection of the `padding` value, its the padding - border width.

fix(Button): padding for all sizes

---

libs/spark/CHANGELOG.md
libs/spark/src/Divider.ts
libs/spark/src/List.ts
libs/spark/src/ListSubheader.ts
libs/spark/src/MenuItem.tsx
libs/spark/src/MenuList.tsx
libs/spark/src/Paper.ts
libs/spark/src/index.ts
libs/spark/src/styles/overrides.ts
libs/spark/stories/menulist.stories.tsx
libs/spark/stories/tag.stories.tsx

Closes #211 .
Adds re-export and stories for `MenuList`. This is the true-est parent component of `MenuItem`'s. The `Menu` component is for controlling `Popper` logic which isn't the point of our styling validations. For more, see https://material-ui.com/components/menus/#menulist-composition.
Six stories from Figma examples
- Basic (plain menu items)
- Sectioned, where a `Divider` appears halfway
- Divider is it's own component, now with style support and a re-export
- Checkboxes
- Avatars
- Scrolling
- note: scrollbar's can't be reliably customized on the Web like the Figma page shows, the most i could do was change the track and thumb colors. Making the width "thin" would have introduced a11y concerns.
- Section Title, where the `ListSubheader` is used
- it's own component, now with …

feat(MenuList): add initial support

---

libs/spark/CHANGELOG.md
libs/spark/src/Autocomplete.tsx
libs/spark/src/index.ts
libs/spark/src/styles/overrides.ts
libs/spark/src/styles/props.ts
libs/spark/stories/autocomplete.stories.tsx

Closes #212.
Implements the "multiple checkbox select with tag rendering" use-case shown in the 'Select Field" Figma page.
This incorporates a lot of recent work:
- `Tag`'s for selected option rendering
- Checkbox items for option rendering
- `MenuItem` styling ported to `Autocomplete`'s `option` classes slot
- it was unfortunate to learn it doesn't actually use `MenuItem`'s for its options!
Adds the story for this single use-case.
This really is just the initial support for this component. This component can do _so_ much, but this use-case is the only one outlined so far in Figma.

feat(Autocomplete): initial support for use-case

---

CHANGELOG.md
libs/spark-icons/CHANGELOG.md
libs/spark-icons/package.json
libs/spark/CHANGELOG.md
libs/spark/package.json
libs/spark/stories/autocomplete.stories.tsx
libs/spark/stories/avatar.stories.tsx
libs/spark/stories/input.stories.tsx
libs/spark/stories/menuitem.stories.tsx
libs/spark/stories/menulist.stories.tsx
libs/spark/stories/select.stories.tsx
libs/spark/stories/tag.stories.tsx
libs/spark/stories/text-field.stories.tsx
package.json

chore(release): 0.11.0

---

CHANGELOG.md
apps/spark-e2e/CHANGELOG.md
libs/spark-icons/CHANGELOG.md
libs/spark-icons/package.json
libs/spark/CHANGELOG.md
libs/spark/package.json
package.json

Adds missing history entry for last PR, whoops.
Removes changelog for the e2e testing app, it's not relevant in any way!
New version bump -- our first fix version that hasn't been overtaken by a feature!

chore(release): 0.11.1

---

.github/workflows/npm-publish.yml

chore(workflow): fix publish action failing on file-watcher limit

---

libs/spark/CHANGELOG.md
libs/spark/src/ListItemSecondaryAction.ts
libs/spark/src/Switch.tsx
libs/spark/src/index.ts
libs/spark/src/styles/overrides.ts
libs/spark/stories/switch.stories.tsx

Closes #147 
Also adds re-exports of `List` and `ListItemSecondaryAction`. I initially used the latter to right-align the `Switch` element in the "Labeled in List" story, however it absolutely positions its children, taking them out of the layout calculation. Thus, you'd have to explicitly account for whether the Switch is `size="small"` or `size="large"`... bad news bears. Instead, the `ListItemIcon` component is much more straightforward, and I copied the relevant styles of that for the story-internal component `ListItemEndIcon`.

feat(Switch): initial implementation

---

libs/spark/CHANGELOG.md
libs/spark/src/Tab.ts
libs/spark/src/TabContext.ts
libs/spark/src/TabList.ts
libs/spark/src/TabPanel.ts
libs/spark/src/Tabs.ts
libs/spark/src/index.ts
libs/spark/src/styles/overrides.ts
libs/spark/src/styles/props.ts
libs/spark/stories/tab.stories.tsx
libs/spark/stories/tabs.stories.tsx

Closes #148 
Re-exports / customizes the core `Tab`, `Tabs` and the experimental `TabContext`, `TabList`, `TabPanel`. The latter of which are emphasized for exclusive use because of their built-in accessibility handling when used as a trio. This is hard to communicate/separate in the story layout, documentation, etc, so I just added a note.

feat(Tabs): initial implementation

---

.github/workflows/npm-publish.yml
libs/spark-icons/scripts/create-typings.js
libs/spark/CHANGELOG.md
libs/spark/tsconfig.build.json
libs/spark/tsconfig.lib.json
package-lock.json
package.json
scripts/babel.config.js
scripts/copy-files.js

Closes #213 and #242 
- Hoist custom `babel.config.js` and `copy-files.js` to top-level `scripts/` directory. Generalize them slightly to fit both use-cases.
- dist files are now written to the libraries exact name, not with `-alt` appended.
- `npm-publish` workflow
- Add descriptive names to each step
- Add version number (stored in GITHUB_REF env var when action is triggered by `release`)
I've run both build processes locally and they work as expected. I also tried importing a component into a story from the `dist/` directory using a deep import (ex: `import Avatar from '../../../dist/libs/spark/Avatar';` and it both rendered correctly and had correct type and props hinting/annotations.

chore: implement common build process for icons and components

---

libs/spark/CHANGELOG.md
libs/spark/src/Avatar.tsx
libs/spark/src/Button.ts
libs/spark/src/Checkbox.tsx
libs/spark/src/FormHelperText.ts
libs/spark/src/FormLabel.ts
libs/spark/src/IconButton.tsx
libs/spark/src/InputAdornment.ts
libs/spark/src/InputBase.tsx
libs/spark/src/ListItemIcon.ts
libs/spark/src/Menu.ts
libs/spark/src/NavBarButton.tsx
libs/spark/src/Pagination.ts
libs/spark/src/Radio.tsx
libs/spark/src/Switch.tsx
libs/spark/src/Tag.tsx

Close #275 
Where possible, these global classes were eliminated. Where elimination wasn't possible, they were changed to select "occurrence" _within_ the class attribute value string (see https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#syntax).

fix: styles using global classes failing

---

libs/spark-icons/CHANGELOG.md
libs/spark-icons/package.json
libs/spark/CHANGELOG.md
libs/spark/package.json

Adjusted markdown of changelogs, versions are second-level headers instead of first-level -- first-level was unreasonably large and nonsensical to have for each one. Also added some periods to top-level sentences.
Removed caret ("^") from the peer dependency of `spark-icons` on `spark`. I found out that by semver, the caret means something different to `0.x` versions since they're pre-stable-api, making it counterintuitive: `Major zero and minor >1: ^0.y.z → 0.y.z - 0.(y+1).0` ([source](https://nodesource.com/blog/semver-tilde-and-caret/)). Since we've already adopted the rule to synchronize the versions of `@prenda/spark` and `@prenda/spark-icons`, I think it will reduce confusion and complexity to eliminate it and modify one of the above steps to account explicitly for the version:
- …

chore(release): v0.16.0

---

.github/workflows/chromatic.yml
.github/workflows/ci:main.yml
.github/workflows/npm-publish.yml
.husky/pre-commit
.husky/pre-push
package.json

Removes testing and linting on both Husky pre-commit and pre-push hook scripts, and improves the format command.
Why remove testing and linting? Both of these processes take an amount of time that reduces developer productivity and increases frustration (speaking from my experience and multiple peers). So, I've moved those checks into the Continuous Integration workflow, increasing its value and utility for contributors (imo, it had low value before; I knew it would pass because I couldn't have pushed it up otherwise).
We don't need to be worried about "every commit should be linted and tested". First, we squash and merge, so it's not important beyond the PR state. Second, in the PR stage, there's good reason to *want* to commit or push failing code: so others can pull it down and …

chore: improve husky hooks and CI workflow

---

libs/spark/src/Collapse/Collapse.stories.tsx
libs/spark/src/Collapse/Collapse.ts
libs/spark/src/Collapse/Collapse.tsx

The `<Collapse>` from MUI v4 only supports vertical orientation, but v5 supports horizontal as well.I'd like to have the functionality immediately for a consuming project, so I essentially copy-pasted the file from right before v5's migration to emotion, added types in the file and adjusted it to our makeStyles / useMergeClasses paradigm.

feat(Collapse): backport v5 changes for horizontal orientation

---

libs/spark/CHANGELOG.md
libs/spark/src/Link/Link.stories.tsx
libs/spark/src/Link/Link.tsx
libs/spark/src/Link/index.ts
libs/spark/src/index.ts

Backport of a PDS v2 component spec using the best palette parallels. This is immediately useful.
Figma spec page: https://www.figma.com/file/6MR4jvUO9jG5pKEogHszHR/?node-id=4284%3A5154
Between "inline" and "standalone", I'm assuming that "inline" will be the more common use-case, so `standalone` is an opt-in prop -- replaces underlying `underline` prop.
All stories spec'd out.

feat(Link): re-exported with custom styles, props

---

libs/spark/CHANGELOG.md
libs/spark/src/theme/__next__palette.stories.tsx
libs/spark/src/theme/__next__palette.ts
libs/spark/src/theme/overrides.ts
libs/spark/src/theme/palette.stories.tsx
libs/spark/src/theme/palette.ts
libs/spark/src/theme/theme.ts
libs/spark/src/theme/themeAugmentation.ts
libs/spark/src/theme/typography.ts

Closes #322
Implements the new palette on a very-clearly experimental field on theme: `theme.__next__palette`. The idea is that when all internal dependencies on `theme.palette` are removed, then the `__next__` will take over. In the meantime, consumers who need this PDS v2 palette will have experimental access to it -- avoiding having to create their own sources of truth.
I reference `globalTokens` and `aliasTokens` based on my reading of Adobe Spectrum's Foundation explainer on design tokens: https://spectrum.adobe.com/page/design-tokens/ . I recommend reading every item under "Foundation", but a particularly enlightening one is International design - Colors https://spectrum.adobe.com/page/international-design/#Colors . I believe that from this, you can see where `aliasTokens` come in. …

feat(__next__palette): PDS v2 palette

---

libs/spark/CHANGELOG.md
libs/spark/src/theme/initialTheme.ts
libs/spark/src/theme/overrides.ts
libs/spark/src/theme/theme.ts
libs/spark/src/theme/themeAugmentation.ts
libs/spark/src/theme/unstable_fontFaces.stories.tsx
libs/spark/src/theme/unstable_fontFaces.ts
libs/spark/src/theme/unstable_palette.stories.tsx
libs/spark/src/theme/unstable_palette.ts
libs/spark/src/theme/unstable_typography.stories.tsx
libs/spark/src/theme/unstable_typography.ts

Fixes `unstable_palette` and `unstable_typography` not being available on the default theme set for the styling utilities. That theme is the `initialTheme` variable, not the final `theme` variable because the latter includes props and classes default that the utilities are required for (circular dep).
The end result is that consumers will be able to access these properties through styling utilities **without** having to render a `ThemeProvider` as an ancestor.

fix(theme): make unstable theme properties available on default theme

---

libs/spark/.eslintrc.json
libs/spark/src/Unstable_Typography/Unstable_Typography.stories.tsx

I noticed the linting was not error'ing on an unused import in a recent file -- not sure why not. This fixes that.

chore(eslint): fix and error on no-unused-vars rule

---

libs/spark/src/Unstable_Typography/Unstable_Typography.tsx

refactor(Unstable_Typography): remove unnecessary `classes` spread

---

libs/spark/CHANGELOG.md
libs/spark/src/index.ts
libs/spark/src/unstable_createSvgIcon.tsx

The same function as before, but using the new `Unstable_SvgIcon`. Also, notably, the utility is defined and exported like a public function, not like an internal one -- the changelog advertises that. I've found that almost all consumers need this at one point or another for some unanticipated one-off.

feat(utils): add unstable_createSvgIcon

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_InputLabel/Unstable_InputLabel.stories.tsx
libs/spark/src/Unstable_InputLabel/Unstable_InputLabel.test.tsx
libs/spark/src/Unstable_InputLabel/Unstable_InputLabel.tsx
libs/spark/src/Unstable_InputLabel/index.ts
libs/spark/src/index.ts
libs/spark/src/utils/StandardProps.ts

Part of #350 .
Necessary pre-req for Input / Select / TextField.
Aside: From now-on, I think Props API changelog entries should just be one line if it would only be a single list item. Doesn't really make sense to have sub-lists when its not a list, just a single item.

feat(Unstable_InputLabel): initial implementation

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Input/Unstable_Input.stories.tsx
libs/spark/src/Unstable_Input/Unstable_Input.test.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_Input/index.ts
libs/spark/src/index.ts
libs/spark/stories/decorators.tsx

Part of #350  .
Notably:
- `success` is an official prop now.
- `(start|end)Adornment` is replaced with a smarter `(leading|trailing)El` (short for "Element") that auto-wraps in `Unstable_InputAdornment`.
Necessary pre-req for Select / TextField

feat(Unstable_Input): initial implementation

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Select/Unstable_Select.tsx
libs/spark/src/Unstable_TextField/Unstable_TextField.stories.tsx
libs/spark/src/Unstable_TextField/Unstable_TextField.test.tsx
libs/spark/src/Unstable_TextField/Unstable_TextField.tsx
libs/spark/src/Unstable_TextField/index.ts
libs/spark/src/index.ts
libs/spark/src/utils/index.ts
libs/spark/src/utils/useId.ts

Part of #350 .
Like `Unstable_Select` (#389 ), this is a re-implementation of Mui's `TextField` component but without the logic and conditional cases related to the several "variants" of Material UI / Design. Removes a lot of heft from the component.

feat(Unstable_TextField): initial implementation

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Button/Unstable_Button.tsx
libs/spark/src/Unstable_Tag/Unstable_Tag.stories.tsx
libs/spark/src/Unstable_Tag/Unstable_Tag.tsx
libs/spark/src/Unstable_Tag/Unstable_TextField.test.tsx
libs/spark/src/Unstable_Tag/index.ts
libs/spark/src/index.ts
libs/spark/src/internal/Unstable_CrossSmall.tsx
libs/spark/src/internal/index.ts

Part of #350 
I winged some things that the Figma did not specify like styling for the "active" pseudo state, the "clickable" styling, plain "icon" prop, etc.
I had to keep the "cross-product" layout for the stories because the complex underlying styles mean we should validate all possibilities for conflicts, and creating individual stories for each is not only way too much code, unfortunately, it's also 2 x 2 x 7 = 28 times more stories for _each_ current "cross-product" story (which there are 10 of). (The special Unicode char in the story names is the a cross product symbol.)

feat(Unstable_Tag): initial implementation

---

libs/spark/.storybook/preview.js

Hopefully this will fix the flip-flopping change of the Tabs indicator animation in Chromatic snapshots.

chore: fix chromatic snapshots changing because of animations

---

libs/spark/src/Unstable_Button/Unstable_Button.stories.tsx

Refactors the stories file for Unstable_Button:
- Custom names for all stories that follow the lowercase prop combo format
- Custom grid template replaced with simple flexboxes (like Unstable_Tag)
- Removed combos that weren't useful (like start/end icon with pseudo states other than disabled -- there's no style changes expected, and no good reason to be concerned).
Each story is still duplicated with a decorating with SparkThemeProvider -- from this, the outstanding issues are clear:
- start/end icon margin shift back-fires under STP
- disabled is wrong under STP
This PR will not aim to fix this issues as the Chromatic snapshots will be reset by these changes.

chore(Unstable_Button): standardize stories

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Typography/Unstable_Typography.stories.tsx
libs/spark/src/Unstable_Typography/Unstable_Typography.tsx
libs/spark/src/theme/unstable_typography.ts
libs/spark/stories/decorators.tsx

Primarily fixes the "T22" typography variant font weight. 
Also fixes the fact that the component wasn't being typed in the right way and the resulting props were losing information, like `variant: string` instead of the true `variant: "display" | "T32" | ...`.
Also rewrites the stories for `Unstable_Typography`. The big example section is already reflected in the story for the theme property story, i.e. `theme/unstable_typography`. The component story now adheres to single stories that just go thru the prop values.

fix(unstable_typography): wrong weight for T22 variant

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Button/Unstable_Button.stories.tsx
libs/spark/src/Unstable_Button/Unstable_Button.tsx

Fixes two issues:
- wonky root styles when disabled under SparkThemeProvider
- wonky start/end icon styles when under SparkThemeProvider
The multiple sections of "double-specificity to override v1 styles" were overwriting each other -- since the key name is the same, adding the same key under a conditional spread will override the previous one. Now there's only one instance of it with everything.
There was some competing custom margin for start/end icons under the v1 theme, so now all margin is fully specified.

fix(Unstable_Button): bad disabled and icon styles under SparkThemeProvider

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_IconButton/Unstable_IconButton.stories.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.test.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
libs/spark/src/Unstable_IconButton/index.ts
libs/spark/src/index.ts
libs/spark/src/internal/Unstable_Filter.tsx
libs/spark/src/internal/index.ts
libs/spark/stories/decorators.tsx

Part of #350 
Added a new decorator in an effort to have Chromatic fully capture the focus indicator -- [margin didn't work in the previous attempt for "Unstable_Button"](https://www.chromatic.com/component?appId=60b7f55f55fbd4004993da4c&csfId=ps-unstable-button--size-by-variant-focus-visible&buildNumber=722&k=6287d0d775c890004a1ce17e-1200-snapshot-true&h=15&b=-5); I'm assuming because either their tool disregards it or there's some margin collapsing going on or something.
_Edit: [the new decorator works](https://www.chromatic.com/test?appId=60b7f55f55fbd4004993da4c&id=628d4ef1de6ce4003a0a8b64)!_

feat(Unstable_IconButton): initial implementation

---

libs/spark/src/Unstable_Button/Unstable_Button.stories.tsx

Implements the new decorator from #408 to ensure the focus indicator is fully contained in Chromatic snapshots.

chore(Unstable_Button): fix snapshots for focus indicator

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Button/Unstable_Button.tsx

The alignments were still off from the attempt to shift the text baseline. Instead of messing with the entire label to adjust the text (requires re-adjusting the icon), we just add a wrap the text in an extra tag and shift that instead. This is better because the icon is always aligned correctly in the button, it's just the text that has a higher baseline than normal (and doesn't appear vertically centered without the shift).
**Before**
**After**

feat(Unstable_Button): improve text baseline shift

---

libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.stories.tsx
libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.tsx
libs/spark/src/internal/Unstable_Alert.tsx

In prep for `Unstable_Banner`, which is another alert like `Unstable_SectionMessage` with different placement/styling, I've pulled out an unstyled, common skeleton that they can share: `Unstable_Alert`.
Also makes a couple changes to the styles of `Unstable_SectionMessage`, mainly setting `display: flex` on the severity icon slot in order to remove the automatic spacing for text ascender and descenders which is not needed since it's an icon. This is an obscure part of CSS! (the effect was that even though the icon height was 24px, the box layout height would be 27-ish px -- this would cause ripple effects across the component styles.

refactor: extract Unstable_Alert from Unstable_SectionMessage

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_IconButton/Unstable_IconButton.stories.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx

Support the ghost icon button variant on inverse background with new color prop ([see figma](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/components?node-id=5080%3A10852)). This is essential for the Banner implementation (up next) (also the Sidebar).

feat(Unstable_IconButton): add color prop

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Button/Unstable_Button.stories.tsx
libs/spark/src/Unstable_Button/Unstable_Button.tsx

(based on #421 )
Add support for `leadingAvatar`.

feat(Unstable_Button): support leadingAvatar

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.tsx
libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_InputLabel/Unstable_InputLabel.tsx

We don't add margin to other components that have box shadow effects, but we did for Input. This is probably best to leave to the consumer or consuming component instead.
This was causing a problem in the upcoming FormControl story / integration for Checkbox / Radio groups since we don't give a radio/checkbox a default margin but we expect the helper text / form label to be aligned -- it wasn't with the left-margins.

feat: remove margin from Input and related components

---

libs/spark/src/Unstable_Checkbox/Unstable_Checkbox.tsx
libs/spark/src/Unstable_FormControlLabel/Unstable_FormControlLabel.tsx
libs/spark/src/Unstable_FormGroup/Unstable_FormGroup.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_Radio/Unstable_Radio.tsx
libs/spark/src/Unstable_RadioGroup/Unstable_RadioGroup.tsx
libs/spark/src/Unstable_Select/Unstable_Select.tsx
libs/spark/src/Unstable_Tag/Unstable_Tag.tsx
libs/spark/src/Unstable_TextField/Unstable_TextField.tsx

Two things:
- props that are assigned types _inside_ of the `forwardRef` function will not have the best typing -- things like discriminated unions of constant strings will show up as just `string`
- strictly typing a ref is problematic when the component is overridable -- the ref should come from the component, but the types can't be that smart. not all these components are overridable, but the principal is sound.
So, all refs are typed as unknown, and ref and props typings are given via generics to `forwardRef`.

feat: improve component typings

---

libs/spark/src/Unstable_Avatar/Unstable_Avatar.tsx
libs/spark/src/Unstable_Banner/Unstable_Banner.tsx
libs/spark/src/Unstable_Button/Unstable_Button.tsx
libs/spark/src/Unstable_FormControlLabel/Unstable_FormControlLabel.tsx
libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.tsx
libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_InputAdornment/Unstable_InputAdornment.tsx
libs/spark/src/Unstable_Link/Unstable_Link.tsx
libs/spark/src/Unstable_RadioGroup/Unstable_RadioGroup.tsx
libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.tsx
libs/spark/src/Unstable_Select/Unstable_Select.tsx
libs/spark/src/Unstable_SvgIcon/Unstable_SvgIcon.tsx
libs/spark/src/Unstable_Tag/Unstable_Tag.tsx
libs/spark/src/Unstable_TextField/Unstable_TextField.tsx
libs/spark/src/Unstable_Typography/Unstable_Typography.tsx

- Add block comment groupings to prop conditional spreads
- Pull focus styles before all props conditions because it's always constant
- Push disabled styles to be **last** so they override anything before it.
- Extract any common style blocks among conditional spreads
- Use `text.disabled` instead of `neutral[0]` where appropriate for text color
- Use `background.inverse` instead of `neutral[600]` where appropriate for background color
- Condition on `aria-expanded` as a prop instead of a DOM attribute

chore: standardize styles

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_FormControl/Unstable_FormControl.stories.tsx
libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
libs/spark/src/Unstable_FormControlLabel/Unstable_FormControlLabel.tsx
libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.tsx
libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx
libs/spark/src/Unstable_Radio/Unstable_Radio.tsx
libs/spark/src/Unstable_RadioGroup/RadioGroupMoreContext.ts
libs/spark/src/Unstable_RadioGroup/Unstable_RadioGroup.stories.tsx
libs/spark/src/Unstable_RadioGroup/Unstable_RadioGroup.tsx
libs/spark/src/Unstable_RadioGroup/index.ts
libs/spark/src/Unstable_RadioGroup/useRadioGroupMore.ts
libs/spark/src/Unstable_TextField/Unstable_TextField.tsx

"Required" radio groups are supported and spec'd [in the HTML spec](https://html.spec.whatwg.org/multipage/input.html#the-required-attribute), but not by Mui's RadioGroup component. We add support here but mirroring Mui's internal "RadioGroupContext" pattern, naming it "RadioGroupMore..." instead. Descendant components like FormControlLabel and Radio are given explicit naming and handling of this prop and context.
Aside: the changelog and some out-of-order entries so I rearranged those as well.

feat: support required radio groups

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_FormGroup/Unstable_FormGroup.tsx

Small change to have wider gaps when in a row for readability. Matches Figma design.

feat(Unstable_FormGroup): widen gap in row layout

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Select/Unstable_Select.stories.tsx
libs/spark/src/Unstable_Select/Unstable_Select.tsx

I had thought the design system's intention was to render the values of _all_ multiple select inputs as Tag's, but that is not the case. So it's now controlled by a prop and off by default. Note that this is technically a breaking change.

feat(Unstable_Select)!: add renderValueAsTag prop

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_CheckboxField/Unstable_CheckboxField.tsx
libs/spark/src/Unstable_CheckboxListItem/Unstable_CheckboxListItem.tsx
libs/spark/src/Unstable_CheckboxMenuItem/Unstable_CheckboxMenuItem.tsx
libs/spark/src/Unstable_FormControlLabel/Unstable_FormControlLabel.tsx
libs/spark/src/Unstable_Menu/Unstable_Menu.tsx
libs/spark/src/Unstable_MenuItem/Unstable_MenuItem.tsx
libs/spark/src/Unstable_MenuList/Unstable_MenuList.tsx
libs/spark/src/Unstable_Paper/Unstable_Paper.tsx
libs/spark/src/Unstable_RadioField/Unstable_RadioField.tsx

Some components were swallowing classes / class name props and/or combining them in the wrong order.

fix: swallowing of class name and wrong ordering

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_CheckboxMenuItem/Unstable_CheckboxMenuItem.stories.tsx
libs/spark/src/Unstable_CheckboxMenuItem/Unstable_CheckboxMenuItem.tsx

Only the menu item will appear with the focus box-shadow, not the inner checkbox.

feat(Unstable_CheckboxMenuItem): remove inner checkbox focus shadow

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_ListItem/Unstable_ListItem.stories.tsx
libs/spark/src/Unstable_ListItem/Unstable_ListItem.tsx

Very useful when having a primary action of a checkbox and needing to indent the entire element (not just the content group) under an item with an indeterminate grouping

feat(Unstable_ListItem): add nested prop

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Tag/Unstable_Tag.tsx

Should be 500, not 600. See [spec ](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/components?node-id=1690%3A71)

fix(Unstable_Tag): wrong font weight for small size

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx

Receives a `margin-bottom: 3px` when under a SparkThemeProvider. This was not well-exemplified by the "(STP)" story since it requires inspect element'ing to see the layout box values.

fix(Unstable_FormLabel): bad margin under STP

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Tooltip/Unstable_Tooltip.tsx

Some consumers (like PW) can't have the transform that eliminates this requirement

fix(Unstable_Tooltip): React is not defined

---

libs/spark/src/Unstable_Checkbox/Unstable_Checkbox.tsx
libs/spark/src/Unstable_FormControlLabel/Unstable_FormControlLabel.tsx
libs/spark/src/Unstable_FormGroup/Unstable_FormGroup.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_Radio/Unstable_Radio.tsx
libs/spark/src/Unstable_RadioGroup/Unstable_RadioGroup.tsx
libs/spark/src/Unstable_Switch/Unstable_Switch.tsx
libs/spark/src/utils/StandardProps.ts
libs/spark/src/withStyles/withStyles.ts

Fixes an issue that first appeared when building Bridge. The "esm" build output is all JS files and thus should be stripped of all type variables. However, `StyledComponentProps` was still appearing in `esm/utils/StandardProps`. We think that TSC has a hard time recognizing something is just a type when its imported and re-exported. This change seems to prevent TSC from making mistakes.

fix: type import/export included in esm JS build

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Typography/Unstable_Typography.tsx

The default of many instances of heading Typography's produces inaccessible pages because almost every design does not use variants as a given heading level. This always has to be determined independent of the heading variant, so we might as well not default to anything but "span".

feat(Typography)!: change variant mapping; make private

---

libs/spark/src/Unstable_SvgIcon/Unstable_SvgIcon.stories.tsx
libs/spark/stories/decorators.tsx

- Make "span" element instead of "div" so it doesn't make snapshots the width of the container.
- Specify "inline-flex" so that child inline elements don't position weirdly (for example, an svg tag will sit above where expected)
Also,
- add to `SvgIcon` inverse color stories

chore(spark): improve inverse background decorator

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Link/Unstable_Link.tsx

Clashing types for `variant` prop from underlying props (Link is typed as extension of Typography) resulting in `never`.

fix(Link): clashing variant type

---

libs/spark/src/Unstable_Banner/Unstable_Banner.tsx
libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.tsx
libs/spark/src/Unstable_SvgIcon/Unstable_SvgIcon.tsx
libs/spark/src/Unstable_Typography/Unstable_Typography.tsx

Improvement on #584 , #585 , #581 , #577
Avoids makeStyles invocations being generated before withStyles and thus having lower priority when they should be higher. Still satisfies that private classes are not visible to consumers by keeping the split class keys and forwarding the public, slot-based on to the props/type-map.

refactor(spark): include private classes in withStyles block

---

libs/spark/.storybook/preview.js
libs/spark/src/Unstable_Tooltip/Unstable_Tooltip.stories.tsx

Iteration on #402 and #582 . 
Removed global styles that would disable / immediately pause animations since Tooltip's snapshots were indeterminate as a result.
Added a delay to Tooltip's snapshots specifically, hoping that after full animation, their end position is determinate.

chore(Tooltip): fix snapshots changing

---

libs/spark-icons/CHANGELOG.md
libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Tooltip/Unstable_Tooltip.stories.tsx

Couple chores:
- Wrong date from v2.0.0-alpha.3 changelog in #614.
- Still getting arbitrary Tooltip snapshot changes

chore(spark): increase Tooltip stories delay & fix changelog date

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Button/Unstable_Button.stories.tsx
libs/spark/src/Unstable_Button/Unstable_Button.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx

Adds support for the `color` prop to Unstable Button, the same as Unstable Icon Button (added in #417). Useful for rendering the ghost variant on an inverse background.

feat(Button): add color prop

---

libs/spark/CHANGELOG.md
libs/spark/src/SparkThemeProvider/SparkThemeProvider.tsx

Changed because of a problem I encountered in a consuming app: the `bootstrap.css` styles were applying after ours because of this injection order.

feat(SparkThemeProvider): inject styles last

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Avatar/Unstable_Avatar.tsx
libs/spark/src/Unstable_AvatarButton/Unstable_AvatarButton.tsx
libs/spark/src/Unstable_Button/Unstable_Button.tsx
libs/spark/src/Unstable_Checkbox/Unstable_CheckboxIcon.tsx
libs/spark/src/Unstable_ContentGroup/Unstable_ContentGroup.stories.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_ListItem/Unstable_ListItem.stories.tsx
libs/spark/src/Unstable_Radio/Unstable_RadioIcon.tsx
libs/spark/src/Unstable_SectionMessage/Unstable_SectionMessage.tsx
libs/spark/src/Unstable_Switch/Unstable_Switch.tsx
libs/spark/src/Unstable_Tab/Unstable_Tab.tsx
libs/spark/src/Unstable_Tag/Unstable_Tag.tsx
libs/spark/src/Unstable_Toast/Unstable_Toast.tsx
libs/spark/src/Unstable_Tooltip/Unstable_Tooltip.tsx
libs/spark/src/theme/initialTheme.ts
libs/spark/src/theme/theme.ts
libs/spark/src/theme/themeAugmentation.ts
libs/spark/src/theme/unstable_elevations.stories.tsx
libs/spark/src/theme/unstable_palette.stories.tsx
libs/spark/src/theme/unstable_radius.stories.tsx
libs/spark/src/theme/unstable_radius.ts

Adds the [border radius foundation spec](https://www.figma.com/file/w9lodWeivyS4GHdBNIYaJr/foundations?node-id=3745%3A59) as a theme property.

feat(theme): add radius

---

libs/spark/src/FormControl/FormControl.ts

Requires type prefix since there's no other named exports that aren't types.

fix(spark): console warning of not-found exports

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Banner/Unstable_Banner.tsx
libs/spark/src/Unstable_Button/Unstable_Button.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
libs/spark/src/Unstable_ModalDialog/Unstable_ModalDialog.tsx
libs/spark/src/Unstable_ModalDialogTitle/Unstable_ModalDialogTitle.tsx
libs/spark/src/Unstable_Toast/Unstable_Toast.tsx

Closes #410 
~Fixes separate issue where background-color was visible through the border-color, making non-stroke buttons appear 2 pixels larger than they should.~
Also fixes separate issue where of Button's being 2px larger than Figma because the stroked variant has a 1px border that's not accounted for in the Figma spec height, meaning that to render it faithfully, it should be 2px larger. As a result, I had made the choice to make every button 2px larger, with just a transparent border color if the variant didn't have a border. This was easier than adjusting the padding to account for border size and all that jazz. This affects both Button and Icon Button. Instead, adequate heights are set for all things and padding is not considered. This was a byproduct of fixes the label issue by …

style(Button): fix text centering and overall height

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
libs/spark/src/Unstable_FormControlExtraContext/Unstable_FormControlExtraContext.ts
libs/spark/src/Unstable_FormControlExtraContext/index.ts
libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.tsx
libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_InputAdornment/Unstable_InputAdornment.tsx
libs/spark/src/Unstable_Select/Unstable_Select.tsx
libs/spark/src/Unstable_TextField/Unstable_TextField.tsx
libs/spark/src/useFormControl_unstable/index.ts
libs/spark/src/useFormControl_unstable/useFormControl_unstable.ts

Abstracts the manual specifications of form control props that aren't specified by MUI like success, and internalizes the accessibility id handling previously owned by Text Field -- this makes Text Field an unnecessary abstraction.

feat(spark): add own form control context

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Banner/Unstable_Banner.tsx
libs/spark/src/Unstable_Button/Unstable_Button.tsx
libs/spark/src/Unstable_IconButton/Unstable_IconButton.tsx
libs/spark/src/Unstable_ModalDialog/Unstable_ModalDialog.tsx
libs/spark/src/Unstable_ModalDialogTitle/Unstable_ModalDialogTitle.tsx
libs/spark/src/Unstable_Toast/Unstable_Toast.tsx

This reverts commit 3cd2d3692bfa8c0f624c202a344c1066eeef2907.
Prevents buttons from overflowing correctly.

Revert "style(Button): fix text centering and overall height (#645)"

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Input/Unstable_Input.tsx

Does two things really. Since we want our inputs to be a different width than browser default, we want to keep the custom width that Input has by default. However it was facing an issue that it would keep this width even when its parent was smaller, and when full width was set -- full width also wasn't handled correctly. To achieve all ends, the width is always 100% and the max width changes instead. This allows full width and auto-adjusting to a smaller-than-desired parent.

fix(Input): fullWidth not working; overflowing parent

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Select/Unstable_Select.tsx

Design changed a little bit, margin was off either way.

fix(Select): icon size, spacing when size="small"

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_ListItem/Unstable_ListItem.tsx
libs/spark/src/Unstable_Tab/Unstable_Tab.tsx

- some consumers, like Prenda World, have Bootstrap.css installed/injected which competes/overrides some of our styles unless specified otherwise.
- also add forgotten changelog message from #663

style: override Bootstrap.css where necessary

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Dropdown/Unstable_Dropdown.spec.tsx
libs/spark/src/Unstable_Dropdown/Unstable_Dropdown.stories.tsx
libs/spark/src/Unstable_Dropdown/Unstable_Dropdown.tsx
libs/spark/src/Unstable_Dropdown/index.ts
libs/spark/src/Unstable_DropdownContext/Unstable_DropdownContext.ts
libs/spark/src/Unstable_DropdownContext/index.ts
libs/spark/src/Unstable_DropdownMenu/Unstable_DropdownMenu.test.tsx
libs/spark/src/Unstable_DropdownMenu/Unstable_DropdownMenu.tsx
libs/spark/src/Unstable_DropdownMenu/index.ts
libs/spark/src/Unstable_DropdownTrigger/Unstable_DropdownTrigger.test.tsx
libs/spark/src/Unstable_DropdownTrigger/Unstable_DropdownTrigger.tsx
libs/spark/src/Unstable_DropdownTrigger/index.ts
libs/spark/src/index.ts
libs/spark/src/useDropdown_unstable/index.ts
libs/spark/src/useDropdown_unstable/useDropdown_unstable.ts

Avoids consumers having to supply the custom components every time. Uses the new, better context-less name patterns and top-level internal-ish components like the Tabs pattern implemented.

feat(Dropdown): add v2 implementation

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_CheckboxListItem/Unstable_CheckboxListItem.test.tsx
libs/spark/src/Unstable_CheckboxListItem/Unstable_CheckboxListItem.tsx

Pretty hacky, but this prevents the following type error when trying to create a click handler function that satisfies the custom signature:
```
const handleClick: React.MouseEventHandler<HTMLLIElement> & ((event: React.MouseEvent<{}, MouseEvent>, value: string, checked: boolean) => void)
Type '(_e: MouseEvent<{}, MouseEvent>, value: string, checked: boolean) => void' is not assignable to type 'MouseEventHandler<HTMLLIElement> & ((event: MouseEvent<{}, MouseEvent>, value: string, checked: boolean) => void)'.
Type '(_e: MouseEvent<{}, MouseEvent>, value: string, checked: boolean) => void' is not assignable to type 'MouseEventHandler<HTMLLIElement>'.ts(2322)
```
The problem lies with the fact that the utility types, Overridable Component and Overridable Props, do not allow for removals or …

fix(CheckboxListItem): underlying `onClick` type preventing custom signature

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.tsx
libs/spark/src/Unstable_CheckboxGroupField/Unstable_CheckboxGroupField.tsx
libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
libs/spark/src/Unstable_FormControlExtraContext/Unstable_FormControlExtraContext.ts
libs/spark/src/Unstable_FormHelperText/Unstable_FormHelperText.tsx
libs/spark/src/Unstable_FormLabel/Unstable_FormLabel.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx
libs/spark/src/Unstable_InputAdornment/Unstable_InputAdornment.tsx
libs/spark/src/Unstable_RadioGroup/Unstable_RadioGroup.tsx
libs/spark/src/Unstable_RadioGroupField/Unstable_RadioGroupField.tsx
libs/spark/src/Unstable_Select/Unstable_Select.tsx
libs/spark/src/Unstable_TextField/Unstable_TextField.tsx
libs/spark/src/useFormControlExtra_unstable/index.ts
libs/spark/src/useFormControlExtra_unstable/useFormControlExtra_unstable.ts
libs/spark/src/useFormControl_unstable/index.ts
libs/spark/src/useFormControl_unstable/useFormControl_unstable.ts

Create a central source of truth for values integrated into the Form Control paradigm / api. Will help to standardize prop values, descriptions, and handling. There are some possible edge cases of mishandling prop values that this PR solves, but they are not detailed here.

feat: standardize Form Control API

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.stories.tsx
libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.tsx

Fix misalignment of input value when default value of `renderMultipleValue` is applied -- unreleased bug from #676, so not noted in changelog.
Fix changing width that can trigger cursor shift, or even overflow, when initially typing.

style(Autocomplete): misaligned input value when `size="small"`; changing width from default `renderMultipleValue`

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.tsx
libs/spark/src/Unstable_CheckboxGroupField/Unstable_CheckboxGroupField.stories.tsx
libs/spark/src/Unstable_FormControl/Unstable_FormControl.tsx
libs/spark/src/Unstable_RadioGroupField/Unstable_RadioGroupField.stories.tsx
libs/spark/src/Unstable_Select/Unstable_Select.tsx

- amend some changelog entries
- [Select] fix an internal typo
- [Select] slightly increase the spacing between the input and icon
- [Select] fix child not increasing to 100% width when full width
- didn't affect styles at-large
- [RadioGroupField] fix a story
- [FormControl] remove default width
- [FormControl] make block-level element
- if kept inline-level element without a default width, it would shrink with a child input like Select
- [CheckboxGroupField] change side-by-side story to be in flex
- consequence of Form Control being block-level

style: change form control related width behaviors

---

libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.tsx

It's a lot easier to standardize the height of an internal "line" of the leading el and input rather than playing with margins. A consistent height allows us to use a center flex align

refactor(Autocomplete): better alignment paradigm

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Autocomplete/Unstable_Autocomplete.tsx

Better results can be achieve in a multi-line view when all of the Input root's children are elements and not wrappers, i.e. leading element, multiple value child, input. When the leading element and multiple value child were wrapped in the "inputLeadingEl" class-applied element, it became its own flexbox and will take up the complete next line when it wraps. This is in contrast to MUI which did not wrapper the multiple value rendering. Now that we've eliminated the wrapper, the input can sit on the same line when the Input root wraps since they're all on the same axis.
This had two side-effects. First, the "height" of each flex line became sensitive. According to the flexbox spec, the height along the main axis is not controllable and is just whatever its largest child in that line is. …

feat(Autocomplete): remove wrapping leading element

---

libs/spark/CHANGELOG.md
libs/spark/src/Unstable_Input/Unstable_Input.stories.tsx
libs/spark/src/Unstable_Input/Unstable_Input.tsx

Design request. Styling felt weird when the user would click into an input (triggering hover and focus visible), start typing (trigger value -> hover), and the input would look kind of disabled at first character because the filled hover is dark.

style(Input): keep background color constant on focus and hover

---

libs/spark/CHANGELOG.md
libs/spark/src/LinearProgress_unstable/LinearProgress_unstable.stories.tsx
libs/spark/src/LinearProgress_unstable/LinearProgress_unstable.test.tsx
libs/spark/src/LinearProgress_unstable/LinearProgress_unstable.tsx
libs/spark/src/LinearProgress_unstable/index.ts
libs/spark/src/index.ts

Initial implementation of a [Linear Progress component](https://v4.mui.com/components/progress/#linear). Removed "buffer" variant because support is complex and we don't seem to need it -- can revisit if we ever do want it. Circular progress will come in follow-up. Supports labels as children. Supports colors (subject to change since there's no spec).
With this component, the migration to a new "unstable" naming scheme is beginning where it appears as a lowercase suffix instead of prefix. This pattern already exists for the unstable hooks.

feat(LinearProgress): initial implementation (unstable)

---

.github/workflows/chromatic.yml
.github/workflows/ci.yml

To debug that the issue in solved in [Disable chromatic turbo snap](https://www.notion.so/Disable-chromatic-turbo-snap-e7570add40eb40aab04505803a4b4bd5?pvs=21) that was encountered in [Update design-system to Nx v19](https://www.notion.so/Update-design-system-to-Nx-v19-22015d683c1745a9ab969f8ee7aee25c?pvs=21) was not a result of the upgrade, I would like to manually trigger the workflow(s) for the main branch.

chore: add manual trigger to workflows

---

.github/workflows/chromatic.yml

This seems to be causing issues with publishing to chromatic. The reason in the error is that preview stats are enabled. I couldn’t figure out how to generate that file. Passing the flag `-- --webpack-stats-jon` did not seem to generate the file in my local `dist/`.

chore: fix chromatic workflow by disabling turbo snap

---

.husky/pre-commit
package-lock.json
package.json

Delete local `.husky`. Follow latest [Husky getting started](https://typicode.github.io/husky/get-started.html). Recreate pre-commit hook decided in #319 .

chore: add pre-commit format check

---

.gitignore

Appeared while I was developing tokens.

chore: ignore storybook build log

---

packages/components/.eslintrc.json
packages/components/package.json
packages/icons/.eslintrc.json
packages/icons/package.json
packages/tokens/.eslintrc.json
packages/tokens/package.json

Ensure that projects with a build target (i.e. components, icons, tokens) properly declare their dependencies.

chore: add project dependency checks

---

packages/components/project.json
packages/icons/project.json
packages/tokens/project.json

Ensure that re-building a project will result in a package.json that reflects the updated dependencies.

chore: fix built projects not containing updated dependencies

---

packages/dataviz/package.json

Closes #763, assuming that the warning about ["duplicate react"](https://legacy.reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) is what's wrong here.

fix(dataviz): duplicate react
